knitwear/knitwear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import Index, Contacts, Payment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('payment/', Payment.as_view(), name='payment'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


knitwear/products/urls.py
from django.urls import path
from products.views import Catalog, ShowProduct

app_name = 'products'

urlpatterns = [
    path('', Catalog.as_view(), name='index'),
    path('<slug:product_slug>/', ShowProduct.as_view(), name='product'),
]

knitwear/users/urls.py
from django.urls import path
from users.views import LoginUser, logout_user, RegisterUser, ProfileUser

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('logout/', logout_user, name='logout'),
]

knitwear/products/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


class ProductBadge(models.Model):
    name = models.CharField(max_length=16, unique=True, verbose_name='Текст')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    color = models.CharField(max_length=8, verbose_name='Цвет')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Плашку'
        verbose_name_plural = 'Плашки'


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='Наименование', unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    sale = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name='Цена со скидкой')
    image = models.ImageField(upload_to='product_images', verbose_name='Картинка')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT, verbose_name='Категория')
    badge = models.ForeignKey(to=ProductBadge, on_delete=models.PROTECT, null=True, blank=True, verbose_name='Плашка')
    is_index = models.BooleanField(default=False, verbose_name='На главном экране')

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    def get_absolute_url(self):
        return reverse('products:product', kwargs={'product_slug': self.slug})

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['time_update']

knitwear/products/forms.py
def main():
    pass
    
if __name__ == '__main__':
    main()

knitwear/products/views.py
from django.views.generic import ListView, DetailView

from products.models import *
from products.utils import DataMixin


class Index(DataMixin, ListView):
    model = Product
    template_name = 'products/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title='Главная страница')
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return Product.objects.filter(is_index=True)


class Catalog(DataMixin, ListView):
    model = Product
    template_name = 'products/catalog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title='Каталог')
        return dict(list(context.items()) + list(c_def.items()))


class ShowProduct(DataMixin, DetailView):
    model = Product
    template_name = 'products/product.html'
    slug_url_kwarg = 'product_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title=context['product'].name)
        return dict(list(context.items()) + list(c_def.items()))


class Payment(DataMixin, ListView):
    model = Product
    template_name = 'products/payment.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title='Оплата')
        return dict(list(context.items()) + list(c_def.items()))


class Contacts(DataMixin, ListView):
    model = Product
    template_name = 'products/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title='Обратная связь')
        return dict(list(context.items()) + list(c_def.items()))

knitwear/products/templates/products/base.html
{% load static %}
{% load products_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous"
    />
    <script
            src="https://kit.fontawesome.com/d2d833681c.js"
            crossorigin="anonymous"
    ></script>
    <title>{{ title }}</title>
    {% block css %} {% endblock%}
</head>
<body>
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img
                    src="{% static 'img/logo.png' %}"
                    alt="logo"
                    width="40"
                    height="40"
            />Зайцева М.Н.
        </a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                {% for m in menu %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url m.url_name %}">{{ m.title }}</a>
                </li>
                {% endfor %}
            </ul>

            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <form class="d-flex" role="search">
                    <input
                            class="form-control me-2"
                            type="search"
                            placeholder="Поиск"
                            aria-label="Search"
                    />
                    <button class="btn btn-outline-success" type="submit">
                        <i
                                class="fa-solid fa-magnifying-glass fa-xl"
                                style="color: #aca3ae"
                        ></i>
                    </button>
                </form>

                <li class="nav-item">
                    <a
                            class="nav-link"
                            href="#"
                            data-bs-toggle="modal"
                            data-bs-target="#modal-cart"
                    >
                        <i
                                class="fa-solid fa-cart-shopping fa-xl"
                                style="color: #aca3ae"
                        ></i>
                    </a>
                    <div
                            class="modal fade"
                            id="modal-cart"
                            tabindex="-1"
                            aria-labelledby="exampleModalLabel"
                            aria-hidden="true"
                    >
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header bg-info">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">
                                        Корзина
                                    </h1>
                                    <button
                                            type="button"
                                            class="btn-close"
                                            data-bs-dismiss="modal"
                                            aria-label="Close"
                                    ></button>
                                </div>
                                <div class="modal-body">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Изображение</th>
                                            <th scope="col">Наименование</th>
                                            <th scope="col">Количество</th>
                                            <th scope="col">Цена</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <th scope="row">1</th>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="modal-footer">
                                    <button
                                            type="button"
                                            class="btn btn-info"
                                            data-bs-dismiss="modal"
                                    >
                                        Продолжить покупки
                                    </button>
                                    <button type="button" class="btn btn-success">
                                        Оформить заказ
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a
                            class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false" href="#"
                    >{{ user.username }}
                        <i
                                class="fa-solid fa-user-tie fa-xl"
                                style="color: #00FA9A"
                        ></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="#">Заказы</a></li>
                        {% if user.is_superuser or user.is_staff %}
                        <li>
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                                Админ-панель
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a
                            class="nav-link"
                            href="{% url 'users:login' %}"
                    >Вход
                        <i
                                class="fa-solid fa-user-tie fa-xl"
                                style="color: #ff0000"
                        ></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock%}

<footer>
    <section class="footer ">
        <div class="container">
            <div class="row text-center">
                <div class="col">
                    <h4>Информация</h4>
                    <div class="list-unstyled">
                        <li><a href="#">Главная</a></li>
                        <li><a href="#">Оплата</a></li>
                        <li><a href="#">Расчет доставки</a></li>
                        <li><a href="#">О нас</a></li>
                    </div>
                </div>
                <div class="col">
                    <h4>Контакты</h4>
                    <div class="list-unstyled">
                        <li><a href="tel:+79611749714">+7-(961)-174-97-14</a></li>
                        <li><a href="tel:+79192880776">+7-(919)-288-07-76</a></li>
                    </div>
                </div>
                <div class="col">
                    <h4>Мы в сети</h4>
                    <div class="footer-icons">
                        <a href="#"
                        ><i
                                class="fa-brands fa-telegram fa-xl"
                                style="color: #0084ff"
                        ></i
                        ></a>
                        <a href="#"
                        ><i
                                class="fa-brands fa-whatsapp fa-xl"
                                style="color: #44ff00"
                        ></i
                        ></a>
                        <a href="#"
                        ><i
                                class="fa-solid fa-envelope fa-xl"
                                style="color: #fff700"
                        ></i
                        ></a>
                        <a href="#"
                        ><i class="fa-brands fa-vk fa-xl" style="color: #0040ff"></i
                        ></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</footer>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"
></script>
</body>
</html>

knitwear/products/templates/products/catalog.html
{% extends 'products/base.html' %} {% load static %} {% load products_tags %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
<link rel="stylesheet" href="{% static 'css/product_cart.css' %}"/>
{% endblock %} {% block content %}
<div class="row">
  <div class="col-4">
    <div id="list-example" class="list-group">
      {% getcats as categories %}
      {% for category in categories %}
      <a class="list-group-item list-group-item-action" href="#{{ category.slug }}">{{ category.name }}</a>
      {% endfor %}
    </div>
  </div>
  <div class="col-8">
    <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
      {% getcats as categories %}
      {% for category in categories %}
      <h4 id="{{ category.slug }}">{{ category.name }}</h4>
      <div class="row">
        {% for product in object_list %}
          <div class="col-lg-4 col-sm-6 mb-3">
            <div class="product-cart">
              <div class="product-thumb">
                <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="" /></a>
              </div>
              <div class="product-details">
                <h4>
                  <a href="{{ product.get_absolute_url }}"
                    >{{ product.name }} {% if product.badge.name %}
                    <span class="badge" color="{{ product.badge.color }}"
                      >{{ product.badge.name }}</span
                    >
                    {% endif %}</a
                  >
                </h4>
                <p>{{ product.description }}</p>
                <div class="product-bottom-details d-flex justify-content-between">
                  <div class="product-price">
                    {% if product.sale %}
                    <small>{{ product.price }}</small> {{ product.sale}} {% else %}
                    {{ product.price }} {% endif %}
                  </div>
                  <div class="product-links">
                    <a href="#"><i class="fa-solid fa-cart-shopping"></i></a>
                    <a href="#"><i class="fa-solid fa-cart-shopping"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

knitwear/products/templates/products/contact.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}
{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Отправить</button>
</form>

{% endblock %}

knitwear/products/templates/products/index.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="{% static 'css/product_cart.css' %}"/>
{% endblock %} {% block content %}
<div class="container-fluid my-carousel">
  <div
    id="carouselExampleIndicators"
    class="carousel slide carousel-fade"
    data-bs-ride="carousel"
    data-bs-interval="3000"
  >
    <div class="carousel-indicators">
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img
          src="{% static 'img/carousel/1.jpg' %}"
          class="d-block w-100"
          alt="..."
        />
      </div>
      <div class="carousel-item">
        <img
          src="{% static 'img/carousel/2.jpg' %}"
          class="d-block w-100"
          alt="..."
        />
      </div>
      <div class="carousel-item">
        <img
          src="{% static 'img/carousel/3.jpg' %}"
          class="d-block w-100"
          alt="..."
        />
      </div>
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<section class="main-content">
  <div class="container">
    <div class="row">
      {% for product in object_list %}
      <div class="col-lg-4 col-sm-6 mb-3">
        <div class="product-cart">
          <div class="product-thumb">
            <a href="#"><img src="{{ product.image.url }}" alt="" /></a>
          </div>
          <div class="product-details">
            <h4>
              <a href="{{ product.get_absolute_url }}"
                >{{ product.name }} {% if product.badge.name %}
                <span class="badge" color="{{ product.badge.color }}"
                  >{{ product.badge.name }}</span
                >
                {% endif %}</a
              >
            </h4>
            <p>{{ product.description }}</p>
            <div class="product-bottom-details d-flex justify-content-between">
              <div class="product-price">
                {% if product.sale %}
                <small>{{ product.price }}</small> {{ product.sale}} {% else %}
                {{ product.price }} {% endif %}
              </div>
              <div class="product-links">
                <a href="#"><i class="fa-solid fa-cart-shopping"></i></a>
                <a href="#"><i class="fa-solid fa-cart-shopping"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

knitwear/products/templates/products/payment.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}
{% block content %}
{{ text }}
{% endblock %}

knitwear/products/templates/products/product.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}

knitwear/products/templates/products/products.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'index.css' %}" />
{% endblock %} {% block content %}
<div class="row">
  <div class="col-4">
    <div
      id="simple-list-example"
      class="d-flex flex-column gap-2 simple-list-example-scrollspy text-center"
    >
      {% for category in categories %}
      <a class="p-1 rounded" href="#simple-list-item">{{ category.name }}</a>
      {% endfor %}
    </div>
  </div>
  <div class="col-8">
    <div
      data-bs-spy="scroll"
      data-bs-target="#simple-list-example"
      data-bs-offset="0"
      data-bs-smooth-scroll="true"
      class="scrollspy-example"
      tabindex="0"
    >
      <h4 id="simple-list-item-1">Item 1</h4>
      <p>...</p>
      <h4 id="simple-list-item-2">Item 2</h4>
      <p>...</p>
      <h4 id="simple-list-item-3">Item 3</h4>
      <p>...</p>
      <h4 id="simple-list-item-4">Item 4</h4>
      <p>...</p>
      <h4 id="simple-list-item-5">Item 5</h4>
      <p>...</p>
    </div>
  </div>
</div>
{% endblock %}