knitwear/knitwear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import Index, Contacts, Payment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('payment/', Payment.as_view(), name='payment'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


knitwear/users/urls.py
from django.urls import path
from users.views import LoginUser, logout_user, RegisterUser, ProfileUser

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('logout/', logout_user, name='logout'),
]

knitwear/users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    SEX_CHOICES = (
        ('m', 'Мужской'),
        ('w', 'Женский'),
    )

    birthday = models.DateField()
    sex = models.CharField(max_length=7, choices=SEX_CHOICES, default='m')


knitwear/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class DateInput(forms.DateInput):
    input_type = 'date'


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'sex', 'username', 'email', 'password1', 'password2')
        widget = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите фамилию'}),
            'birthday': forms.SelectDateWidget(attrs={'class': 'form-control', 'placeholder': 'Введите день рождения'}),
            'sex': forms.RadioSelect(attrs={'class': 'form-control', 'placeholder': 'Выберите пол'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите логин'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        }


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'sex', 'username', 'email')
        widget = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': DateInput(attrs={'class': 'form-control'}),
            'sex': forms.RadioSelect(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'readonly': True}),
        }

knitwear/users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from products.utils import DataMixin
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm


class LoginUser(DataMixin, LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('index')


class RegisterUser(DataMixin, CreateView):
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect('index')


class ProfileUser(DataMixin, CreateView):
    form_class = UserProfileForm
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_context(title="Профиль")
        return dict(list(context.items()) + list(c_def.items()))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

knitwear/users/templates/users/login.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}
{% block content %}

<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors %}
                    <div class="alert
                    {% if messages %} alert-success {% else %} alert-warning {% endif %}
                     alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3></div>
                    <div class="card-body">
                        <form action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.username.id_for_label }}" class="form-label"
                                >Логин</label
                                >
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.password.id_for_label }}" class="form-label"
                                >Пароль</label
                                >
                                {{ form.password }}
                            </div>
                            <div class="mb-3 form-check">
                                <input
                                        type="checkbox"
                                        class="form-check-input"
                                        id="password"
                                />
                                <label class="form-check-label" for="password"
                                >Показать пароль</label
                                >
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a href="#">
                                    <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                </a>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт?
                                    Зарегистрируйся!</a></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

knitwear/users/templates/users/profile.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <form action="{% url 'users:profile' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.birthday.id_for_label }}">
                                    День рождения
                                </label>
                                {{ form.birthday }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.sex.id_for_label }}">
                                    Пол
                                </label>
                                {{ form.sex }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                Адрес электронной почты
                            </label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

knitwear/users/templates/users/registration.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
{% endblock %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.birthday.id_for_label }}">
                                                День рождения
                                            </label>
                                            {{ form.birthday }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.sex.id_for_label }}">
                                                Пол
                                            </label>
                                            {{ form.sex }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">
                                    Уже есть аккаунт? Авторизоваться
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}